[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.10.4",
    "fastapi[standard]>=0.112.2",
    "pytest>=8.3.2",
    "supabase>=2.7.3",
]
